package org.wallentines.serverswitcher;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.wallentines.mcore.MidnightCoreAPI;
import org.wallentines.mdcfg.ConfigObject;
import org.wallentines.mdcfg.ConfigSection;
import org.wallentines.mdcfg.codec.FileWrapper;
import org.wallentines.mdcfg.serializer.ConfigContext;
import org.wallentines.mdproxy.jwt.FileKeyStore;
import org.wallentines.mdproxy.jwt.KeyStore;
import org.wallentines.mdproxy.jwt.KeyType;
import org.wallentines.midnightlib.registry.Identifier;
import org.wallentines.midnightlib.registry.RegistryBase;
import org.wallentines.midnightlib.registry.StringRegistry;
import org.wallentines.midnightlib.types.ResettableSingleton;
import org.wallentines.midnightlib.types.Singleton;

import java.io.*;
import java.security.GeneralSecurityException;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.util.Random;

public class ServerSwitcher extends ServerSwitcherAPI {

    private static final Logger LOGGER = LoggerFactory.getLogger("ServerSwitcher");

    public static final Identifier RECONNECT_COOKIE = new Identifier("mdp", "rc");
    private final RegistryBase<String, ServerInfo> serverRegistry;
    private final FileWrapper<ConfigObject> config;
    private final KeyStore keyStore;
    private String serverName;
    private String namespace;
    private PublicKey key;
    private boolean clearReconnect;
    private int jwtTimeout;

    private static final ConfigSection DEFAULT_CONFIG = new ConfigSection()
            .with("server", "lobby")
            .with("namespace", "default")
            .with("servers", new ConfigSection())
            .with("clear_reconnect_cookie", true)
            .with("jwt_expire_sec", 5);

    private ServerSwitcher(File configFolder) {

        this.keyStore = new FileKeyStore(configFolder, FileKeyStore.DEFAULT_TYPES);

        if(!configFolder.isDirectory() && !configFolder.mkdirs()) {
            throw new IllegalStateException("Unable to create config directory!");
        }

        this.config = MidnightCoreAPI.FILE_CODEC_REGISTRY.findOrCreate(ConfigContext.INSTANCE, "config", configFolder, DEFAULT_CONFIG);
        if(!this.config.getFile().exists()) {
            this.config.save();
        }

        this.serverRegistry = new StringRegistry<>();

        reload();
    }

    @Override
    public void reload() {

        this.config.load();
        ConfigSection sec = config.getRoot().asSection();

        this.serverName = sec.getString("server");
        this.namespace = sec.getString("namespace");

        serverRegistry.clear();
        ConfigSection servers = sec.getSection("servers");

        boolean requiresKey = false;

        for(String s : servers.getKeys()) {
            ServerInfo info = servers.get(s, ServerInfo.SERIALIZER);
            if(info.proxyBackend() != null) requiresKey = true;
            serverRegistry.register(s, info);
        }

        if(requiresKey) {
            key = keyStore.getKey("key", KeyType.RSA_PUBLIC);
            if (key == null) {
                LOGGER.warn("There is no public key available in the data folder, but MidnightProxy backend switching was requested! Please put an RSA public key generated by your MidnightProxy server in the data folder in a file called key.pub");
            }
        }

        this.clearReconnect = sec.getBoolean("clear_reconnect_cookie");
        this.jwtTimeout = sec.getInt("jwt_timeout_ms");
    }

    public RegistryBase<String, ServerInfo> getServerRegistry() {
        return serverRegistry;
    }

    public String getServerName() {
        return serverName;
    }

    public PublicKey getKey() {
        return key;
    }

    public static void init(File configFolder) {
        INSTANCE.set(new ServerSwitcher(configFolder));
    }

    public static void shutdown() {
        INSTANCE.reset();
    }

    public boolean shouldClearReconnect() {
        return clearReconnect;
    }

    public int getJWTTimeout() {
        return jwtTimeout;
    }

}
